#!/usr/bin/env bash
# Script that installs Nginx server
sudo apt-get update
sudo apt-get -y install nginx

# Configuer Ngnix to listen on port 80
sudo sed -i 's/listen\80\ default_server/listen\ 80/' /etc/nginx/sites-available/default

# Restart Ngnix
sudo /etc/init.d/nginx restart

# Create a test index.html file
sudo bash -c 'echo "Hello World!" > /var/www?html/index.html'

# Test if Nginx is serving the test index.html file
response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost)
if [ $response -eq 200 ]; then
	echo "Nginx is successfully installed and serving the test index.html file."
else
	echo "There was an error installing and configuring Nginx."
fi
