#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
sudo touch /etc/haproxy/haproxy.cfg

sudo cat <<EOT >> /etc/haproxy/haproxy.cfg
frontend my_frontend
	bind *:80
	default_backend my_backend

backend my_backend
	balance roundrobin
	server 145621-web-01 34.229.189.48:80 check
	server 145621-web-02 54.152.203.53:80 check
EOT

# Enable HAProxy
sudo systemctl enable haproxy

# Restart HAProxy
sudo systemctl restart haproxy
