#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
echo "
frontend my_frontend
	bind *:80
	default_backend my_backend

backend my_backend
	balance roundrobin
	server 145621-web-01 34.229.189.48:80 check
	server 145621-web-02 54.152.203.53:80 check
" >> /etc/haproxy/haproxy.cfg

# Enable HAProxy
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

# Restart HAProxy
sudo service restart haproxy
