#!/usr/bin/env bash
# generates a MySQl dumb and creates a compressed archive out of it

MYSQL_PASSWORD="$1"

# Filename format for the backup
FILE_NAME="$(date +"%d-%m-%Y").tar.gz"

# Dump the MySQL databases and compress them
mysqldump --user=root --password="$MYSQL_PASSWORD" --all-databases > backup.sql
tar -czf "$FILE_NAME" "backup.sql"
